dist: xenial
language: php
php: 
  # - '5.6'
  - '7.1'
  - '7.2'
  - '7.3'  
  # cannot make 7.3 work : there is an unidentified error leading to HTTP 503 when using HttpRequest calls
  
services:
# make the `mysql` binary available
  - mysql

env:
  # make environment variables available
  # bash: `$SITE_FOLDER` 
  # PHP : `getenv('SITE_FOLDER');` 
  global:
    - DB_NAME="qinoa"
    
before_script:
  # travis DB user is `root`, password is empty and host is `127.0.0.1`
  # - mysql -e "create database IF NOT EXISTS $DB_NAME;" -uroot
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('test') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root  
  # install apache2
  - chmod +x .travis/*.sh
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then .travis/init-php7.3.sh; else .travis/init-php.sh; fi

  
  
script: 
  # check that mandatory directories are present and have correct access rights set
  - php run.php --do=test_fs-consistency
  # check ability to connect to the dbms service
  - php run.php --do=test_db-connectivity
  # create an empty database 
  - php run.php --do=init_db  
  # initialise database with demo data
  - php run.php --do=init_package --package=core
  # run test units
  - php run.php --do=test_package --package=qinoa