language: php
php: 
  - '5.6'
  - '7.1'
  - '7.2'
  - '7.3'  
  
services:
# make the `mysql` binary available
  - mysql

env:
  # make environment variables available
  # bash: `$SITE_FOLDER` 
  # PHP : `getenv('SITE_FOLDER');` 
  global:
    - DB_NAME="qinoa"
    
before_script:
  # travis DB user is `root`, password is empty and host is `127.0.0.1`
  - mysql -e "create database IF NOT EXISTS $DB_NAME;" -uroot
  
script: 
  # check connectivity to db service
  - php run.php --get=test_fs-consistency
  # check connectivity to db service
  - php run.php --get=test_db-connectivity
  # initialise database with demo data
  - php run.php --do=test_db-init
  # run test units
  - php run.php --get=test_testunit
